# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Angel/Desktop/hil/pfc3ph/vivado_lite/pfc_3ph_lite.srcs/sources_1/bd/design_1/ip/design_1_compar_tc_0_1/design_1_compar_tc_0_1.xci
# IP: The module: 'design_1_compar_tc_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Angel/Desktop/hil/pfc3ph/vivado_lite/pfc_3ph_lite.gen/sources_1/bd/design_1/ip/design_1_compar_tc_0_1/clock_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_compar_tc_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Angel/Desktop/hil/pfc3ph/vivado_lite/pfc_3ph_lite.srcs/sources_1/bd/design_1/ip/design_1_compar_tc_0_1/design_1_compar_tc_0_1.xci
# IP: The module: 'design_1_compar_tc_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Angel/Desktop/hil/pfc3ph/vivado_lite/pfc_3ph_lite.gen/sources_1/bd/design_1/ip/design_1_compar_tc_0_1/clock_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_compar_tc_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
