SLStudio.Utils.RemoveHighlighting(get_param('HDL_pfc_gold_fi', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_HDL_pfc_gold_fi', 'handle'));
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/adder', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/dtc', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/gain', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/dtc1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Multiply-Add', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Multiply-Add', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Constant', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Constant', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Subtract', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Subtract', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Subtract1', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Subtract1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/OR', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/OR', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Equal', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Equal', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1_const', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3_const', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain3', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain3', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1_out_dtc', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3_out_dtc', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/t', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1/tapped_delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/t1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed/sumStateEqnComp', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed/dtc', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed/t', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed1/State_switch', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed1/t', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/dot_product_9', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/dot_product_7', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/dot_product_7', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/dot_product_6', 0, 1, '');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
