open_system('gm_HDL_pfc_gold_fi');
open_system('HDL_pfc_gold_fi');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/adder', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/adder', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/dtc', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/dtc', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/gain', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/gain', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/dtc1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/dtc1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Multiply-Add', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Multiply-Add', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Multiply-Add', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Multiply-Add', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Constant', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Constant', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Constant', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Constant', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Subtract', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Subtract', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Subtract', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Subtract', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Subtract1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Subtract1', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Subtract1', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Subtract1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/OR', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/OR', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/OR', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/OR', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Equal', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Equal', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Equal', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Equal', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1_const', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1_const', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain1', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain1', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3_const', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3_const', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain3', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain3', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain3', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain3', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1_out_dtc', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain1_out_dtc', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3_out_dtc', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/Gain3_out_dtc', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/t', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1/tapped_delay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/t1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed/t1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/FET_CTRL/crp_temp_streamed', 0, 1, 'Streaming Group 1');
