// -------------------------------------------------------------
// 
// File Name: hdl_prj2\hdlsrc\HDL_pfc_gold_fi_og\simscape_system_tc.v
// Created: 2025-05-12 20:29:20
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simscape_system_tc
// Source Path: simscape_system_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_1_1   : identical to clk_enable
// enb_1_49_0  : 49x slower than clk with last phase
// enb_1_49_1  : 49x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simscape_system_tc
          (clk,
           reset,
           clk_enable,
           enb,
           enb_1_1_1,
           enb_1_49_0,
           enb_1_49_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb;
  output  enb_1_1_1;
  output  enb_1_49_0;
  output  enb_1_49_1;


  reg [5:0] count49;  // ufix6
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_49_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_49_1_1;


  assign enb = clk_enable;

  assign enb_1_1_1 = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 48
  always @(posedge clk)
    begin : counter_49_process
      if (reset == 1'b1) begin
        count49 <= 6'b000001;
      end
      else begin
        if (clk_enable) begin
          if (count49 >= 6'b110000) begin
            count49 <= 6'b000000;
          end
          else begin
            count49 <= count49 + 6'b000001;
          end
        end
      end
    end

  assign comp_0_tmp = count49 == 6'b110000;

  assign phase_0_tmp = comp_0_tmp & clk_enable;

  always @(posedge clk)
    begin : phase_delay_process
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end

  assign enb_1_49_0_1 = phase_0 & clk_enable;

  assign enb_1_49_0 = enb_1_49_0_1;

  assign comp_1_tmp = count49 == 6'b000000;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk)
    begin : phase_delay_1_process
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end

  assign enb_1_49_1_1 = phase_1 & clk_enable;

  assign enb_1_49_1 = enb_1_49_1_1;

endmodule  // simscape_system_tc

