open_system('gm_HDL_pfc_gold_fi');
open_system('HDL_pfc_gold_fi');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/Gain1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/Gain1', 0, 1, 'Sharing Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain1', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain1', 0, 1, 'Sharing Group 1');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain3', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Gain3', 0, 1, 'Sharing Group 1');
