open_system('gm_HDL_pfc_gold_fi');
open_system('HDL_pfc_gold_fi');
clearhighlighting;
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/dot_product_7', 'user5');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/dot_product_7', 0, 1, 'Sharing Group 5');
hilite_system('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user5');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Sharing Group 5');
