open_system('HDL_pfc_gold_fi');
open_system('gm_HDL_pfc_gold_fi');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/Discrete-Time Integrator_reg', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/Discrete-Time Integrator_reg', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/in0_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/Equal', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Equal', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/in1_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/State', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/State', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/in0_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in0_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in1_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in2_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in2_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in5_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in5_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in6_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in6_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in7_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in7_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay29', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay29', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay29', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay29', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay25', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay25', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay25', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay25', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay28', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay28', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay28', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay28', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay1', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay26', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay26', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay26', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay26', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay27', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay27', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay27', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay27', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay30', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay30', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay30', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay30', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay24', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay24', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay24', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay24', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay3', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay3', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay4', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay4', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay5', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay5', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay7', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay7', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay7', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay7', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay8', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay10', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay10', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay10', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay10', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay12', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay12', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay12', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay12', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in4_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in4_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay22', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay22', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay22', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay22', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in7_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in7_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay9', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay9', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay9', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay9', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in6_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in6_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay6', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay6', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay6', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in5_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in5_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay21', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay21', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay21', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay21', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in4_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in4_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay18', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay18', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay18', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay18', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in3_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in3_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay23', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay23', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay23', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay23', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in2_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in2_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in1_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in1_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay14', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay14', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay14', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay14', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in7_repeat2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in7_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay17', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay17', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay17', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay17', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in4_repeat2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in4_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay15', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay15', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay15', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay15', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in3_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in3_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay11', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay11', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay11', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay11', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in2_repeat2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in2_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay2', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in1_repeat2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in1_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay13', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay13', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay13', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay13', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in0_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in0_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay19', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay19', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay19', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay19', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in0_repeat2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in0_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay16', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/Delay16', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay16', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8/Delay16', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in3_repeat2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8/in3_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/enb_counter_le_1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/enb_counter_le_1', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/enb_counter_eq_23', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/enb_counter_eq_23', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/enb_counter_eq_24', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL/crp_temp_shared/enb_counter_eq_24', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/tappedDelay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_6', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_ge_2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_ge_2', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_7', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_7', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_eq_8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_eq_8', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/tappedDelay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_6', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_ge_2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_ge_2', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_7', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_7', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_eq_8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_eq_8', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/tappedDelay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_19', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_19', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_ge_2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_ge_2', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_20', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_20', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_eq_21', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_eq_21', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/tappedDelay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_19', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_19', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_ge_2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_ge_2', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_20', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_20', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_eq_21', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_eq_21', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/real2uint8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi/simscape_system/real2uint8', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/real2uint8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in0_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in1_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in2_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in2_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in3_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in3_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in4_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in4_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in5_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in5_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in6_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in6_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in7_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in7_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in8_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in8_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in9_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in9_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in0_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in0_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in1_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in1_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in2_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in2_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in3_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in3_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in4_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in4_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in5_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in5_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in6_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in6_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in7_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/in7_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/FET_CTRL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('HDL_pfc_gold_fi/simscape_system/FET_CTRL', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/FET_CTRL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem', 'user1');
annotate_port('gm_HDL_pfc_gold_fi/simscape_system/simscape_system/HDL Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('HDL_pfc_gold_fi/simscape_system/HDL Subsystem', 'user1');
annotate_port('HDL_pfc_gold_fi/simscape_system/HDL Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
