create_clock -period 83.333 -name sysclk -waveform {0.000 41.667} [get_ports sysclk]
set_property PACKAGE_PIN M9 [get_ports sysclk]
set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
set_property PACKAGE_PIN D2 [get_ports sysrst]
set_property IOSTANDARD LVCMOS33 [get_ports sysrst]
create_clock -period 15.151515 -name TCK -waveform {0.000 7.575758} [get_pins u_BSCANE2/TCK]
set_clock_groups -asynchronous -group TCK -group [get_clocks -include_generated_clocks clk_out1_clk_wiz_0]
