// -------------------------------------------------------------
// 
// File Name: .\hdlsrc\amc_simulator\cnter.v
// Created: 2025-04-21 11:28:28
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cnter
// Source Path: amc_simulator/amc_simulator/cnter
// Hierarchy Level: 1
// Model version: 3.14
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cnter
          (clk,
           rst,
           enb,
           y);


  input   clk;
  input   rst;
  input   enb;
  output  [15:0] y;  // uint16


  reg [15:0] Output_out1;  // uint16
  wire [15:0] Increment_Real_World_out1;  // uint16
  wire [15:0] Wrap_To_Zero_out1;  // uint16


  Increment_Real_World u_Increment_Real_World (.u(Output_out1),  // uint16
                                               .y(Increment_Real_World_out1)  // uint16
                                               );
  Wrap_To_Zero u_Wrap_To_Zero (.U(Increment_Real_World_out1),  // uint16
                               .Y(Wrap_To_Zero_out1)  // uint16
                               );
  always @(posedge clk)
    begin : Output_rsvd_process
      if (rst == 1'b1) begin
        Output_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Output_out1 <= Wrap_To_Zero_out1;
        end
      end
    end
  assign y = Output_out1;

endmodule  // cnter

