SLStudio.Utils.RemoveHighlighting(get_param('HDL_pfc_gold_fi_og', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_HDL_pfc_gold_fi_og', 'handle'));
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t2', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t3', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t4', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t5', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t6', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t7', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t8', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t9', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t10', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/Discrete-Time Integrator_reg', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/in0_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Discrete-Time Integrator_saturate', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/adder', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/dtc', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/gain', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/dtc1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Multiply-Add', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Multiply-Add', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Constant', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Constant', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Subtract', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Subtract', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Subtract1', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Subtract1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/OR', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/OR', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Equal', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Equal', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Gain1_const', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Gain1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Gain1', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Gain1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Gain3_const', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Gain3', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Gain3', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Gain3', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Gain1_out_dtc', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Gain3_out_dtc', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/t', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1/tapped_delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/t1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/in1_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/State', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/in0_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/sumStateEqnComp', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/dtc', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/t', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/State_switch', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/t', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in3_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay291', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay251', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay31', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay8', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay8', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay12', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay12', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in4_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in3_repeat1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay24', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay24', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay5', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay5', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay1', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in2_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay16', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay16', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in2_repeat1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay111', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay2', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay2', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay6', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay6', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in4_repeat1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat2', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat2', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay9', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay9', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay4', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay4', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat3', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat3', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay22', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay22', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/dot_product_9', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/dot_product_7', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/dot_product_7', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/dot_product_6', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/counter', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_ge_13', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_le_19', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_ge_14', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_le_191', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_eq_20', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/counter', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_le_5', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_le_6', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_eq_6', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Equal', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Equal', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/counter', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_4', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_5', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_eq_5', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_ge_32', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_36', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_eq_37', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/counter', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_6', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_ge_7', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_12', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_eq_13', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/counter', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_6', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_ge_8', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_13', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_eq_14', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/counter', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_19', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_ge_8', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_26', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_eq_27', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/tappedDelay', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/counter', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_19', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_ge_7', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_25', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_eq_26', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in0_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in1_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in2_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in3_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in4_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in5_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in6_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in7_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in8_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in9_repeat', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in5_repeat1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in6_repeat1', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL', 0, 1, '');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem', 0, 1, '');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem', 0, 1, '');
