open_system('gm_HDL_pfc_gold_fi_og');
open_system('HDL_pfc_gold_fi_og');
clearhighlighting;
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/sumStateEqnComp', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/sumStateEqnComp', 0, 1, 'Streaming Group 2');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user2');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/dtc', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/dtc', 0, 1, 'Streaming Group 2');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user2');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay/tapped_delay', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/t', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/t', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/State_switch', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/State_switch', 0, 1, 'Streaming Group 3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay/tapped_delay', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay', 0, 1, 'Streaming Group 3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/t', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/t', 0, 1, 'Streaming Group 3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1', 0, 1, 'Streaming Group 3');
