open_system('HDL_pfc_gold_fi_og');
open_system('gm_HDL_pfc_gold_fi_og');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t3', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t4', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t5', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t6', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t7', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t7', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t9', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t9', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/t10', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/t10', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/Discrete-Time Integrator_reg', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/Discrete-Time Integrator_reg', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/in0_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/in1_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/State', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/State', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/in0_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/Fixed-Point State-Space', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in3_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in3_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay291', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay291', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay251', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay251', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay31', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay31', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay8', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay12', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay12', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay12', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay12', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in4_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in4_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in3_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in3_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay24', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay24', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay24', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay24', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay5', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay5', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay1', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in2_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in2_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay16', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay16', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay16', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay16', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in2_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in2_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay111', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay111', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay2', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay6', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay6', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay6', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in4_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in4_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat2', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay9', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay9', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay9', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay9', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay4', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay4', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat3', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in1_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat3', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/in0_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay22', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8/Delay22', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay22', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8/Delay22', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_ge_13', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_ge_13', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_le_19', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_le_19', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_ge_14', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_ge_14', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_le_191', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_le_191', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_eq_20', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed/enb_counter_eq_20', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_le_5', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_le_5', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_le_6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_le_6', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_eq_6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/streaming_partition_streamed1/enb_counter_eq_6', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Equal', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Equal', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL/Equal', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/tappedDelay1', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_4', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_4', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_5', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_5', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_eq_5', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_eq_5', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_ge_32', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_ge_32', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_36', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_le_36', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_eq_37', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL/crp_temp_streamed/enb_counter_eq_37', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/tappedDelay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_6', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_ge_7', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_ge_7', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_12', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_le_12', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_eq_13', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product/hNNewMatrixB_shared/enb_counter_eq_13', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/tappedDelay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_6', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_6', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_ge_8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_ge_8', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_13', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_le_13', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_eq_14', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product1/hNNewMatrixA_shared/enb_counter_eq_14', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/tappedDelay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_19', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_19', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_ge_8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_ge_8', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_26', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_le_26', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_eq_27', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product2/hNNewMatrixC_shared/enb_counter_eq_27', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/tappedDelay', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/counter', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_19', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_19', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_ge_7', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_ge_7', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_25', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_le_25', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_eq_26', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/Sparse Matrix-Vector Product3/hNNewMatrixD_shared/enb_counter_eq_26', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/real2uint8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/real2uint8', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/real2uint8', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in0_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in1_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in2_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in2_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in3_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in3_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in4_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in4_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in5_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in5_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in6_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in6_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in7_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in7_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in8_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in8_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in9_repeat', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in9_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in5_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in5_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in6_repeat1', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/in6_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/FET_CTRL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/FET_CTRL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
