open_system('gm_HDL_pfc_gold_fi_og');
open_system('HDL_pfc_gold_fi_og');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed/Sum State Equation', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed/Sum State Equation', 0, 1, 'Streaming Group 1');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/mat_mux/Sum State Equation', 'user1');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/mat_mux/Sum State Equation', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed/tappedDelay', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed/t', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed', 'user1');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/Reshape', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/Reshape', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/Delay_switch', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/Delay_switch', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/Reshape1', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/Reshape1', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/tappedDelay/tapped_delay', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/tappedDelay', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/tappedDelay', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/t', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/t', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/tappedDelay1/tapped_delay', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/tappedDelay1/tapped_delay', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/tappedDelay1', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/tappedDelay1', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/t1', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1/t1', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1', 'user2');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed1', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2/Sum Output Equation', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2/Sum Output Equation', 0, 1, 'Streaming Group 3');
hilite_system('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/mat_mux/Sum Output Equation', 'user3');
annotate_port('HDL_pfc_gold_fi_og/simscape_system/HDL Subsystem/mat_mux/Sum Output Equation', 0, 1, 'Streaming Group 3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2/tappedDelay/tapped_delay', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2/tappedDelay', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2/tappedDelay', 0, 1, 'Streaming Group 3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2/t', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2/t', 0, 1, 'Streaming Group 3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2', 'user3');
annotate_port('gm_HDL_pfc_gold_fi_og/simscape_system/simscape_system/HDL Subsystem/mat_mux/streaming_partition_streamed2', 0, 1, 'Streaming Group 3');
