// -------------------------------------------------------------
// 
// File Name: C:\Users\Angel\Desktop\hil\ips\MCP_DRIVER\hdlsrc\int2bin_sdi\simfcn1.v
// Created: 2025-05-02 20:52:58
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simfcn1
// Source Path: 
// Hierarchy Level: 2
// Model version: 3.111
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simfcn1
          (vx,
           cont_bits2_0,
           cont_bits2_1,
           cont_bits2_2,
           cont_bits2_3,
           cont_bits2_4,
           cont_bits2_5,
           cont_bits2_6,
           cont_bits2_7,
           cont_bits2_8,
           cont_bits2_9,
           cont_bits2_10,
           cont_bits2_11);


  input   [15:0] vx;  // uint16
  output  [7:0] cont_bits2_0;  // uint8
  output  [7:0] cont_bits2_1;  // uint8
  output  [7:0] cont_bits2_2;  // uint8
  output  [7:0] cont_bits2_3;  // uint8
  output  [7:0] cont_bits2_4;  // uint8
  output  [7:0] cont_bits2_5;  // uint8
  output  [7:0] cont_bits2_6;  // uint8
  output  [7:0] cont_bits2_7;  // uint8
  output  [7:0] cont_bits2_8;  // uint8
  output  [7:0] cont_bits2_9;  // uint8
  output  [7:0] cont_bits2_10;  // uint8
  output  [7:0] cont_bits2_11;  // uint8


  wire tmp;
  wire [15:0] tmp_1;  // uint16
  wire [7:0] tmp_2;  // uint8
  wire tmp_3;
  wire [15:0] tmp_4;  // uint16
  wire [7:0] tmp_5;  // uint8
  wire tmp_6;
  wire [15:0] tmp_7;  // uint16
  wire [7:0] tmp_8;  // uint8
  wire tmp_9;
  wire [15:0] tmp_10;  // uint16
  wire [7:0] tmp_11;  // uint8
  wire tmp_12;
  wire [15:0] tmp_13;  // uint16
  wire [7:0] tmp_14;  // uint8
  wire tmp_15;
  wire [15:0] tmp_16;  // uint16
  wire [7:0] tmp_17;  // uint8
  wire tmp_18;
  wire [15:0] tmp_19;  // uint16
  wire [7:0] tmp_20;  // uint8
  wire tmp_21;
  wire [15:0] tmp_22;  // uint16
  wire [7:0] tmp_23;  // uint8
  wire tmp_24;
  wire [15:0] tmp_25;  // uint16
  wire [7:0] tmp_26;  // uint8
  wire tmp_27;
  wire [15:0] tmp_28;  // uint16
  wire [7:0] tmp_29;  // uint8
  wire tmp_30;
  wire [15:0] tmp_31;  // uint16
  wire [7:0] tmp_32;  // uint8
  wire tmp_33;
  wire [15:0] tmp_34;  // uint16
  wire [7:0] tmp_35;  // uint8
  wire [7:0] cont_bits2 [0:11];  // uint8 [12]


  // MATLAB Function 'simfcn1'
  assign tmp = vx[0] != 1'b0;
  assign tmp_1 = {15'b0, tmp};

  assign tmp_2 = tmp_1[7:0];

  assign tmp_3 = vx[1] != 1'b0;

  assign tmp_4 = {15'b0, tmp_3};

  assign tmp_5 = tmp_4[7:0];

  assign tmp_6 = vx[2] != 1'b0;

  assign tmp_7 = {15'b0, tmp_6};

  assign tmp_8 = tmp_7[7:0];

  assign tmp_9 = vx[3] != 1'b0;

  assign tmp_10 = {15'b0, tmp_9};

  assign tmp_11 = tmp_10[7:0];

  assign tmp_12 = vx[4] != 1'b0;

  assign tmp_13 = {15'b0, tmp_12};

  assign tmp_14 = tmp_13[7:0];

  assign tmp_15 = vx[5] != 1'b0;

  assign tmp_16 = {15'b0, tmp_15};

  assign tmp_17 = tmp_16[7:0];

  assign tmp_18 = vx[6] != 1'b0;

  assign tmp_19 = {15'b0, tmp_18};

  assign tmp_20 = tmp_19[7:0];

  assign tmp_21 = vx[7] != 1'b0;

  assign tmp_22 = {15'b0, tmp_21};

  assign tmp_23 = tmp_22[7:0];

  assign tmp_24 = vx[8] != 1'b0;

  assign tmp_25 = {15'b0, tmp_24};

  assign tmp_26 = tmp_25[7:0];

  assign tmp_27 = vx[9] != 1'b0;

  assign tmp_28 = {15'b0, tmp_27};

  assign tmp_29 = tmp_28[7:0];

  assign tmp_30 = vx[10] != 1'b0;

  assign tmp_31 = {15'b0, tmp_30};

  assign tmp_32 = tmp_31[7:0];

  assign tmp_33 = vx[11] != 1'b0;

  assign tmp_34 = {15'b0, tmp_33};

  assign tmp_35 = tmp_34[7:0];

  assign cont_bits2[0] = tmp_35;
  assign cont_bits2[1] = tmp_32;
  assign cont_bits2[2] = tmp_29;
  assign cont_bits2[3] = tmp_26;
  assign cont_bits2[4] = tmp_23;
  assign cont_bits2[5] = tmp_20;
  assign cont_bits2[6] = tmp_17;
  assign cont_bits2[7] = tmp_14;
  assign cont_bits2[8] = tmp_11;
  assign cont_bits2[9] = tmp_8;
  assign cont_bits2[10] = tmp_5;
  assign cont_bits2[11] = tmp_2;

  assign cont_bits2_0 = cont_bits2[0];

  assign cont_bits2_1 = cont_bits2[1];

  assign cont_bits2_2 = cont_bits2[2];

  assign cont_bits2_3 = cont_bits2[3];

  assign cont_bits2_4 = cont_bits2[4];

  assign cont_bits2_5 = cont_bits2[5];

  assign cont_bits2_6 = cont_bits2[6];

  assign cont_bits2_7 = cont_bits2[7];

  assign cont_bits2_8 = cont_bits2[8];

  assign cont_bits2_9 = cont_bits2[9];

  assign cont_bits2_10 = cont_bits2[10];

  assign cont_bits2_11 = cont_bits2[11];

endmodule  // simfcn1

